// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.17.3
// source: entitypb/talent.proto

package entitypb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BodySizeDataType struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height    int32  `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Bust      int32  `protobuf:"varint,2,opt,name=Bust,proto3" json:"Bust,omitempty"`
	Waist     int32  `protobuf:"varint,3,opt,name=Waist,proto3" json:"Waist,omitempty"`
	Hips      int32  `protobuf:"varint,4,opt,name=Hips,proto3" json:"Hips,omitempty"`
	BodyType  int32  `protobuf:"varint,5,opt,name=BodyType,proto3" json:"BodyType,omitempty"`
	HairType  string `protobuf:"bytes,6,opt,name=HairType,proto3" json:"HairType,omitempty"`
	HairColor string `protobuf:"bytes,7,opt,name=HairColor,proto3" json:"HairColor,omitempty"`
	EyesColor string `protobuf:"bytes,8,opt,name=EyesColor,proto3" json:"EyesColor,omitempty"`
	ShoesSize int32  `protobuf:"varint,9,opt,name=ShoesSize,proto3" json:"ShoesSize,omitempty"`
}

func (x *BodySizeDataType) Reset() {
	*x = BodySizeDataType{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *BodySizeDataType) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BodySizeDataType) ProtoMessage() {}

func (x *BodySizeDataType) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BodySizeDataType.ProtoReflect.Descriptor instead.
func (*BodySizeDataType) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{0}
}

func (x *BodySizeDataType) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *BodySizeDataType) GetBust() int32 {
	if x != nil {
		return x.Bust
	}
	return 0
}

func (x *BodySizeDataType) GetWaist() int32 {
	if x != nil {
		return x.Waist
	}
	return 0
}

func (x *BodySizeDataType) GetHips() int32 {
	if x != nil {
		return x.Hips
	}
	return 0
}

func (x *BodySizeDataType) GetBodyType() int32 {
	if x != nil {
		return x.BodyType
	}
	return 0
}

func (x *BodySizeDataType) GetHairType() string {
	if x != nil {
		return x.HairType
	}
	return ""
}

func (x *BodySizeDataType) GetHairColor() string {
	if x != nil {
		return x.HairColor
	}
	return ""
}

func (x *BodySizeDataType) GetEyesColor() string {
	if x != nil {
		return x.EyesColor
	}
	return ""
}

func (x *BodySizeDataType) GetShoesSize() int32 {
	if x != nil {
		return x.ShoesSize
	}
	return 0
}

type TalentRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Age              int32                  `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	BirthDate        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Gender           string                 `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Verified         bool                   `protobuf:"varint,7,opt,name=Verified,proto3" json:"Verified,omitempty"`
	BodySize         *BodySizeDataType      `protobuf:"bytes,8,opt,name=BodySize,proto3" json:"BodySize,omitempty"`
	ProductionType   []string               `protobuf:"bytes,9,rep,name=ProductionType,proto3" json:"ProductionType,omitempty"`
	Languages        []string               `protobuf:"bytes,10,rep,name=Languages,proto3" json:"Languages,omitempty"`
	Skills           []string               `protobuf:"bytes,11,rep,name=Skills,proto3" json:"Skills,omitempty"`
	Keywords         []string               `protobuf:"bytes,12,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	DataType         string                 `protobuf:"bytes,13,opt,name=DataType,proto3" json:"DataType,omitempty"`
	PhotoProfile     string                 `protobuf:"bytes,14,opt,name=PhotoProfile,proto3" json:"PhotoProfile,omitempty"`
	Password         string                 `protobuf:"bytes,15,opt,name=Password,proto3" json:"Password,omitempty"`
	CodeVerification string                 `protobuf:"bytes,16,opt,name=CodeVerification,proto3" json:"CodeVerification,omitempty"`
}

func (x *TalentRequest) Reset() {
	*x = TalentRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalentRequest) ProtoMessage() {}

func (x *TalentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalentRequest.ProtoReflect.Descriptor instead.
func (*TalentRequest) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{1}
}

func (x *TalentRequest) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TalentRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TalentRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TalentRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *TalentRequest) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *TalentRequest) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *TalentRequest) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *TalentRequest) GetBodySize() *BodySizeDataType {
	if x != nil {
		return x.BodySize
	}
	return nil
}

func (x *TalentRequest) GetProductionType() []string {
	if x != nil {
		return x.ProductionType
	}
	return nil
}

func (x *TalentRequest) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *TalentRequest) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *TalentRequest) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *TalentRequest) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *TalentRequest) GetPhotoProfile() string {
	if x != nil {
		return x.PhotoProfile
	}
	return ""
}

func (x *TalentRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *TalentRequest) GetCodeVerification() string {
	if x != nil {
		return x.CodeVerification
	}
	return ""
}

type TalentResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Email            string                 `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	Name             string                 `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	Address          string                 `protobuf:"bytes,3,opt,name=Address,proto3" json:"Address,omitempty"`
	Age              int32                  `protobuf:"varint,4,opt,name=Age,proto3" json:"Age,omitempty"`
	BirthDate        *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=BirthDate,proto3" json:"BirthDate,omitempty"`
	Gender           string                 `protobuf:"bytes,6,opt,name=Gender,proto3" json:"Gender,omitempty"`
	Verified         bool                   `protobuf:"varint,7,opt,name=Verified,proto3" json:"Verified,omitempty"`
	BodySize         *BodySizeDataType      `protobuf:"bytes,8,opt,name=BodySize,proto3" json:"BodySize,omitempty"`
	ProductionType   []string               `protobuf:"bytes,9,rep,name=ProductionType,proto3" json:"ProductionType,omitempty"`
	Languages        []string               `protobuf:"bytes,10,rep,name=Languages,proto3" json:"Languages,omitempty"`
	Skills           []string               `protobuf:"bytes,11,rep,name=Skills,proto3" json:"Skills,omitempty"`
	Keywords         []string               `protobuf:"bytes,12,rep,name=Keywords,proto3" json:"Keywords,omitempty"`
	DataType         string                 `protobuf:"bytes,13,opt,name=DataType,proto3" json:"DataType,omitempty"`
	PhotoProfile     string                 `protobuf:"bytes,14,opt,name=PhotoProfile,proto3" json:"PhotoProfile,omitempty"`
	Password         string                 `protobuf:"bytes,15,opt,name=Password,proto3" json:"Password,omitempty"`
	CodeVerification string                 `protobuf:"bytes,16,opt,name=CodeVerification,proto3" json:"CodeVerification,omitempty"`
	Id               string                 `protobuf:"bytes,17,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *TalentResponse) Reset() {
	*x = TalentResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalentResponse) ProtoMessage() {}

func (x *TalentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalentResponse.ProtoReflect.Descriptor instead.
func (*TalentResponse) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{2}
}

func (x *TalentResponse) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *TalentResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *TalentResponse) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *TalentResponse) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *TalentResponse) GetBirthDate() *timestamppb.Timestamp {
	if x != nil {
		return x.BirthDate
	}
	return nil
}

func (x *TalentResponse) GetGender() string {
	if x != nil {
		return x.Gender
	}
	return ""
}

func (x *TalentResponse) GetVerified() bool {
	if x != nil {
		return x.Verified
	}
	return false
}

func (x *TalentResponse) GetBodySize() *BodySizeDataType {
	if x != nil {
		return x.BodySize
	}
	return nil
}

func (x *TalentResponse) GetProductionType() []string {
	if x != nil {
		return x.ProductionType
	}
	return nil
}

func (x *TalentResponse) GetLanguages() []string {
	if x != nil {
		return x.Languages
	}
	return nil
}

func (x *TalentResponse) GetSkills() []string {
	if x != nil {
		return x.Skills
	}
	return nil
}

func (x *TalentResponse) GetKeywords() []string {
	if x != nil {
		return x.Keywords
	}
	return nil
}

func (x *TalentResponse) GetDataType() string {
	if x != nil {
		return x.DataType
	}
	return ""
}

func (x *TalentResponse) GetPhotoProfile() string {
	if x != nil {
		return x.PhotoProfile
	}
	return ""
}

func (x *TalentResponse) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *TalentResponse) GetCodeVerification() string {
	if x != nil {
		return x.CodeVerification
	}
	return ""
}

func (x *TalentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type TalentUpdaterequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id           *ID            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	RequestsData *TalentRequest `protobuf:"bytes,2,opt,name=requestsData,proto3" json:"requestsData,omitempty"`
}

func (x *TalentUpdaterequest) Reset() {
	*x = TalentUpdaterequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TalentUpdaterequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TalentUpdaterequest) ProtoMessage() {}

func (x *TalentUpdaterequest) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TalentUpdaterequest.ProtoReflect.Descriptor instead.
func (*TalentUpdaterequest) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{3}
}

func (x *TalentUpdaterequest) GetId() *ID {
	if x != nil {
		return x.Id
	}
	return nil
}

func (x *TalentUpdaterequest) GetRequestsData() *TalentRequest {
	if x != nil {
		return x.RequestsData
	}
	return nil
}

type SuccessResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *SuccessResponses) Reset() {
	*x = SuccessResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SuccessResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SuccessResponses) ProtoMessage() {}

func (x *SuccessResponses) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SuccessResponses.ProtoReflect.Descriptor instead.
func (*SuccessResponses) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{4}
}

func (x *SuccessResponses) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ID struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *ID) Reset() {
	*x = ID{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ID) ProtoMessage() {}

func (x *ID) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ID.ProtoReflect.Descriptor instead.
func (*ID) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{5}
}

func (x *ID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Pagination struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Limit int64 `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Page  int64 `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
}

func (x *Pagination) Reset() {
	*x = Pagination{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Pagination) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Pagination) ProtoMessage() {}

func (x *Pagination) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Pagination.ProtoReflect.Descriptor instead.
func (*Pagination) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{6}
}

func (x *Pagination) GetLimit() int64 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *Pagination) GetPage() int64 {
	if x != nil {
		return x.Page
	}
	return 0
}

type ListTalentsResponses struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ListTalents []*TalentResponse `protobuf:"bytes,1,rep,name=listTalents,proto3" json:"listTalents,omitempty"`
}

func (x *ListTalentsResponses) Reset() {
	*x = ListTalentsResponses{}
	if protoimpl.UnsafeEnabled {
		mi := &file_entitypb_talent_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListTalentsResponses) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTalentsResponses) ProtoMessage() {}

func (x *ListTalentsResponses) ProtoReflect() protoreflect.Message {
	mi := &file_entitypb_talent_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTalentsResponses.ProtoReflect.Descriptor instead.
func (*ListTalentsResponses) Descriptor() ([]byte, []int) {
	return file_entitypb_talent_proto_rawDescGZIP(), []int{7}
}

func (x *ListTalentsResponses) GetListTalents() []*TalentResponse {
	if x != nil {
		return x.ListTalents
	}
	return nil
}

var File_entitypb_talent_proto protoreflect.FileDescriptor

var file_entitypb_talent_proto_rawDesc = []byte{
	0x0a, 0x15, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x70, 0x62, 0x2f, 0x74, 0x61, 0x6c, 0x65, 0x6e,
	0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0xfa, 0x01, 0x0a, 0x10, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x42, 0x75, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x42, 0x75, 0x73, 0x74,
	0x12, 0x14, 0x0a, 0x05, 0x57, 0x61, 0x69, 0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x05, 0x57, 0x61, 0x69, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x48, 0x69, 0x70, 0x73, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x48, 0x69, 0x70, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x42, 0x6f,
	0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x42, 0x6f,
	0x64, 0x79, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x48, 0x61, 0x69, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x48, 0x61, 0x69, 0x72, 0x54, 0x79,
	0x70, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x48, 0x61, 0x69, 0x72, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x48, 0x61, 0x69, 0x72, 0x43, 0x6f, 0x6c, 0x6f, 0x72,
	0x12, 0x1c, 0x0a, 0x09, 0x45, 0x79, 0x65, 0x73, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x08, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x09, 0x45, 0x79, 0x65, 0x73, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1c,
	0x0a, 0x09, 0x53, 0x68, 0x6f, 0x65, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x09, 0x53, 0x68, 0x6f, 0x65, 0x73, 0x53, 0x69, 0x7a, 0x65, 0x22, 0x8a, 0x04, 0x0a,
	0x0d, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65,
	0x6d, 0x61, 0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x41, 0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x42, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74,
	0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74,
	0x61, 0x6d, 0x70, 0x52, 0x09, 0x42, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16,
	0x0a, 0x06, 0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69,
	0x65, 0x64, 0x12, 0x33, 0x0a, 0x08, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x42, 0x6f, 0x64,
	0x79, 0x53, 0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x42,
	0x6f, 0x64, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12,
	0x1c, 0x0a, 0x09, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03,
	0x28, 0x09, 0x52, 0x09, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a,
	0x06, 0x53, 0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64,
	0x73, 0x12, 0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a,
	0x0c, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x0e, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0c, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c,
	0x65, 0x12, 0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0f, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2a, 0x0a,
	0x10, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x9b, 0x04, 0x0a, 0x0e, 0x74, 0x61,
	0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61,
	0x69, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x12, 0x10, 0x0a, 0x03, 0x41, 0x67, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x41,
	0x67, 0x65, 0x12, 0x38, 0x0a, 0x09, 0x42, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d,
	0x70, 0x52, 0x09, 0x42, 0x69, 0x72, 0x74, 0x68, 0x44, 0x61, 0x74, 0x65, 0x12, 0x16, 0x0a, 0x06,
	0x47, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x47, 0x65,
	0x6e, 0x64, 0x65, 0x72, 0x12, 0x1a, 0x0a, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64,
	0x12, 0x33, 0x0a, 0x08, 0x42, 0x6f, 0x64, 0x79, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x42, 0x6f, 0x64, 0x79, 0x53,
	0x69, 0x7a, 0x65, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x52, 0x08, 0x42, 0x6f, 0x64,
	0x79, 0x53, 0x69, 0x7a, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x50, 0x72, 0x6f, 0x64, 0x75, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x18, 0x09, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x50,
	0x72, 0x6f, 0x64, 0x75, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x18, 0x0a, 0x20, 0x03, 0x28, 0x09,
	0x52, 0x09, 0x4c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67, 0x65, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x53,
	0x6b, 0x69, 0x6c, 0x6c, 0x73, 0x18, 0x0b, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x53, 0x6b, 0x69,
	0x6c, 0x6c, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x18,
	0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x08, 0x4b, 0x65, 0x79, 0x77, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x1a, 0x0a, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x18, 0x0d, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x44, 0x61, 0x74, 0x61, 0x54, 0x79, 0x70, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x50,
	0x68, 0x6f, 0x74, 0x6f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x50, 0x72, 0x6f, 0x66, 0x69, 0x6c, 0x65, 0x12,
	0x1a, 0x0a, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x0f, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x50, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72, 0x64, 0x12, 0x2a, 0x0a, 0x10, 0x43,
	0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x18,
	0x10, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x43, 0x6f, 0x64, 0x65, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x11, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x6a, 0x0a, 0x13, 0x74, 0x61, 0x6c, 0x65, 0x6e,
	0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x2e, 0x49, 0x44, 0x52, 0x02, 0x69, 0x64, 0x12, 0x38, 0x0a, 0x0c, 0x72, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x73, 0x44, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x14, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x52, 0x0c, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x73, 0x44,
	0x61, 0x74, 0x61, 0x22, 0x2c, 0x0a, 0x10, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x22, 0x14, 0x0a, 0x02, 0x49, 0x44, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x36, 0x0a, 0x0a, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x69, 0x6d, 0x69, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70,
	0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x22,
	0x4f, 0x0a, 0x14, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x12, 0x37, 0x0a, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x54,
	0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x68,
	0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x52, 0x0b, 0x6c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73,
	0x32, 0xb1, 0x02, 0x0a, 0x0d, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69,
	0x63, 0x65, 0x12, 0x2e, 0x0a, 0x09, 0x41, 0x64, 0x64, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12,
	0x14, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x09, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x49, 0x44,
	0x22, 0x00, 0x12, 0x2f, 0x0a, 0x09, 0x47, 0x65, 0x74, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12,
	0x09, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x49, 0x44, 0x1a, 0x15, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x2e, 0x74, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x22, 0x00, 0x12, 0x45, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x54, 0x61, 0x6c,
	0x65, 0x6e, 0x74, 0x12, 0x1a, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x74, 0x61, 0x6c, 0x65,
	0x6e, 0x74, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x72, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00, 0x12, 0x34, 0x0a, 0x0c, 0x44, 0x65,
	0x6c, 0x65, 0x74, 0x65, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x12, 0x09, 0x2e, 0x68, 0x65, 0x6c,
	0x6c, 0x6f, 0x2e, 0x49, 0x44, 0x1a, 0x17, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x73, 0x75,
	0x63, 0x63, 0x65, 0x73, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x73, 0x22, 0x00,
	0x12, 0x42, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x54, 0x61, 0x6c, 0x65, 0x6e,
	0x74, 0x73, 0x12, 0x11, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x70, 0x61, 0x67, 0x69, 0x6e,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x1b, 0x2e, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x2e, 0x4c, 0x69,
	0x73, 0x74, 0x54, 0x61, 0x6c, 0x65, 0x6e, 0x74, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x73, 0x22, 0x00, 0x42, 0x0c, 0x5a, 0x0a, 0x2e, 0x2f, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_entitypb_talent_proto_rawDescOnce sync.Once
	file_entitypb_talent_proto_rawDescData = file_entitypb_talent_proto_rawDesc
)

func file_entitypb_talent_proto_rawDescGZIP() []byte {
	file_entitypb_talent_proto_rawDescOnce.Do(func() {
		file_entitypb_talent_proto_rawDescData = protoimpl.X.CompressGZIP(file_entitypb_talent_proto_rawDescData)
	})
	return file_entitypb_talent_proto_rawDescData
}

var file_entitypb_talent_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_entitypb_talent_proto_goTypes = []interface{}{
	(*BodySizeDataType)(nil),      // 0: hello.BodySizeDataType
	(*TalentRequest)(nil),         // 1: hello.talentRequest
	(*TalentResponse)(nil),        // 2: hello.talentResponse
	(*TalentUpdaterequest)(nil),   // 3: hello.talentUpdaterequest
	(*SuccessResponses)(nil),      // 4: hello.successResponses
	(*ID)(nil),                    // 5: hello.ID
	(*Pagination)(nil),            // 6: hello.pagination
	(*ListTalentsResponses)(nil),  // 7: hello.ListTalentsResponses
	(*timestamppb.Timestamp)(nil), // 8: google.protobuf.Timestamp
}
var file_entitypb_talent_proto_depIdxs = []int32{
	8,  // 0: hello.talentRequest.BirthDate:type_name -> google.protobuf.Timestamp
	0,  // 1: hello.talentRequest.BodySize:type_name -> hello.BodySizeDataType
	8,  // 2: hello.talentResponse.BirthDate:type_name -> google.protobuf.Timestamp
	0,  // 3: hello.talentResponse.BodySize:type_name -> hello.BodySizeDataType
	5,  // 4: hello.talentUpdaterequest.id:type_name -> hello.ID
	1,  // 5: hello.talentUpdaterequest.requestsData:type_name -> hello.talentRequest
	2,  // 6: hello.ListTalentsResponses.listTalents:type_name -> hello.talentResponse
	1,  // 7: hello.talentService.AddTalent:input_type -> hello.talentRequest
	5,  // 8: hello.talentService.GetTalent:input_type -> hello.ID
	3,  // 9: hello.talentService.UpdateTalent:input_type -> hello.talentUpdaterequest
	5,  // 10: hello.talentService.DeleteTalent:input_type -> hello.ID
	6,  // 11: hello.talentService.GetListTalents:input_type -> hello.pagination
	5,  // 12: hello.talentService.AddTalent:output_type -> hello.ID
	2,  // 13: hello.talentService.GetTalent:output_type -> hello.talentResponse
	4,  // 14: hello.talentService.UpdateTalent:output_type -> hello.successResponses
	4,  // 15: hello.talentService.DeleteTalent:output_type -> hello.successResponses
	7,  // 16: hello.talentService.GetListTalents:output_type -> hello.ListTalentsResponses
	12, // [12:17] is the sub-list for method output_type
	7,  // [7:12] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_entitypb_talent_proto_init() }
func file_entitypb_talent_proto_init() {
	if File_entitypb_talent_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_entitypb_talent_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*BodySizeDataType); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitypb_talent_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalentRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitypb_talent_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalentResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitypb_talent_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TalentUpdaterequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitypb_talent_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SuccessResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitypb_talent_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ID); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitypb_talent_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Pagination); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_entitypb_talent_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListTalentsResponses); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_entitypb_talent_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_entitypb_talent_proto_goTypes,
		DependencyIndexes: file_entitypb_talent_proto_depIdxs,
		MessageInfos:      file_entitypb_talent_proto_msgTypes,
	}.Build()
	File_entitypb_talent_proto = out.File
	file_entitypb_talent_proto_rawDesc = nil
	file_entitypb_talent_proto_goTypes = nil
	file_entitypb_talent_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// TalentServiceClient is the client API for TalentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type TalentServiceClient interface {
	AddTalent(ctx context.Context, in *TalentRequest, opts ...grpc.CallOption) (*ID, error)
	GetTalent(ctx context.Context, in *ID, opts ...grpc.CallOption) (*TalentResponse, error)
	UpdateTalent(ctx context.Context, in *TalentUpdaterequest, opts ...grpc.CallOption) (*SuccessResponses, error)
	DeleteTalent(ctx context.Context, in *ID, opts ...grpc.CallOption) (*SuccessResponses, error)
	GetListTalents(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*ListTalentsResponses, error)
}

type talentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewTalentServiceClient(cc grpc.ClientConnInterface) TalentServiceClient {
	return &talentServiceClient{cc}
}

func (c *talentServiceClient) AddTalent(ctx context.Context, in *TalentRequest, opts ...grpc.CallOption) (*ID, error) {
	out := new(ID)
	err := c.cc.Invoke(ctx, "/hello.talentService/AddTalent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talentServiceClient) GetTalent(ctx context.Context, in *ID, opts ...grpc.CallOption) (*TalentResponse, error) {
	out := new(TalentResponse)
	err := c.cc.Invoke(ctx, "/hello.talentService/GetTalent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talentServiceClient) UpdateTalent(ctx context.Context, in *TalentUpdaterequest, opts ...grpc.CallOption) (*SuccessResponses, error) {
	out := new(SuccessResponses)
	err := c.cc.Invoke(ctx, "/hello.talentService/UpdateTalent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talentServiceClient) DeleteTalent(ctx context.Context, in *ID, opts ...grpc.CallOption) (*SuccessResponses, error) {
	out := new(SuccessResponses)
	err := c.cc.Invoke(ctx, "/hello.talentService/DeleteTalent", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *talentServiceClient) GetListTalents(ctx context.Context, in *Pagination, opts ...grpc.CallOption) (*ListTalentsResponses, error) {
	out := new(ListTalentsResponses)
	err := c.cc.Invoke(ctx, "/hello.talentService/GetListTalents", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// TalentServiceServer is the server API for TalentService service.
type TalentServiceServer interface {
	AddTalent(context.Context, *TalentRequest) (*ID, error)
	GetTalent(context.Context, *ID) (*TalentResponse, error)
	UpdateTalent(context.Context, *TalentUpdaterequest) (*SuccessResponses, error)
	DeleteTalent(context.Context, *ID) (*SuccessResponses, error)
	GetListTalents(context.Context, *Pagination) (*ListTalentsResponses, error)
}

// UnimplementedTalentServiceServer can be embedded to have forward compatible implementations.
type UnimplementedTalentServiceServer struct {
}

func (*UnimplementedTalentServiceServer) AddTalent(context.Context, *TalentRequest) (*ID, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddTalent not implemented")
}
func (*UnimplementedTalentServiceServer) GetTalent(context.Context, *ID) (*TalentResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTalent not implemented")
}
func (*UnimplementedTalentServiceServer) UpdateTalent(context.Context, *TalentUpdaterequest) (*SuccessResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateTalent not implemented")
}
func (*UnimplementedTalentServiceServer) DeleteTalent(context.Context, *ID) (*SuccessResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteTalent not implemented")
}
func (*UnimplementedTalentServiceServer) GetListTalents(context.Context, *Pagination) (*ListTalentsResponses, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetListTalents not implemented")
}

func RegisterTalentServiceServer(s *grpc.Server, srv TalentServiceServer) {
	s.RegisterService(&_TalentService_serviceDesc, srv)
}

func _TalentService_AddTalent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TalentRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalentServiceServer).AddTalent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.talentService/AddTalent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalentServiceServer).AddTalent(ctx, req.(*TalentRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalentService_GetTalent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalentServiceServer).GetTalent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.talentService/GetTalent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalentServiceServer).GetTalent(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalentService_UpdateTalent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TalentUpdaterequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalentServiceServer).UpdateTalent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.talentService/UpdateTalent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalentServiceServer).UpdateTalent(ctx, req.(*TalentUpdaterequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalentService_DeleteTalent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalentServiceServer).DeleteTalent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.talentService/DeleteTalent",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalentServiceServer).DeleteTalent(ctx, req.(*ID))
	}
	return interceptor(ctx, in, info, handler)
}

func _TalentService_GetListTalents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Pagination)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(TalentServiceServer).GetListTalents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/hello.talentService/GetListTalents",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(TalentServiceServer).GetListTalents(ctx, req.(*Pagination))
	}
	return interceptor(ctx, in, info, handler)
}

var _TalentService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "hello.talentService",
	HandlerType: (*TalentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AddTalent",
			Handler:    _TalentService_AddTalent_Handler,
		},
		{
			MethodName: "GetTalent",
			Handler:    _TalentService_GetTalent_Handler,
		},
		{
			MethodName: "UpdateTalent",
			Handler:    _TalentService_UpdateTalent_Handler,
		},
		{
			MethodName: "DeleteTalent",
			Handler:    _TalentService_DeleteTalent_Handler,
		},
		{
			MethodName: "GetListTalents",
			Handler:    _TalentService_GetListTalents_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "entitypb/talent.proto",
}
